<a href="https://colab.research.google.com/github/yskim1230/SuanLab-Numpy/blob/main/_NumPy_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 한번에 제대로 배우기



---



## NumPy 특징

* Numerical Python의 약자
* 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
* 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
* 정교한 브로드캐스팅(broadcasting) 기능
* 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
* 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
* 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [1]:
import numpy as np
np.__version__


'1.22.4'



---



## 배열 생성

### 리스트로 배열 만들기


In [2]:
a1 = np.array([1, 2, 3, 4, 5])

print(a1)
print(type(a1)) # ndarray
print(a1.shape) # 1차원
print(a1[0], a1[1], a1[2])
a1[0] = 4
print(a1)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3
[4 2 3 4 5]


In [3]:
a2 = np.array([ [1,2,3], [4,5,6] ,[7,8,9] ])
print(a2)
print(a2.shape) # 2차원

print(a2[0,0],a2[0,1], a2[0,2]) 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 2 3


In [4]:
a3 = np.array([
    
     [ [1,2,3,] , [4,5,6], [7,8,9]],
     [ [1,2,3,] , [4,5,6], [7,8,9]],
     [ [1,2,3,] , [4,5,6], [7,8,9]]
    
    
])
print(a3)
print(a3.shape) # 3차원


[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


### 배열 생성 및 초기화

* `zeros()`: 모든 요소를 0으로 초기화

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `ones()`: 모든 요소를 1로 초기화

In [6]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* `full()`: 모든 요소를 지정한 값으로 초기화

In [7]:
np.full((3,3), 1.23)

array([[1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23]])

* `eye()`: 단위행렬(identity matrix) 생성
  + 주대각선의 원소가 모두 1이고 나머지 원소는 모두 0인 정사각 행렬

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

* `tri()`: 삼각행렬 생성

In [9]:
np.tri(3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

* `empty()`: 초기화되지 않은 배열 생성
  + 초기화가 없어서 배열 생성비용 저렴하고 빠름
  + 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음

In [10]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

* `_like()`: 지정된 배열과 shape가 같은 행렬 생성
  + `np.zeros_like()`
  + `np.ones_like()`
  + `np.full_like()`
  + `np.empty_like()`

In [11]:
print(a1)
np.zeros_like(a1)


[4 2 3 4 5]


array([0, 0, 0, 0, 0])

In [12]:
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [13]:
print(a3)
np.full_like(a3,10)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]],

       [[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]]])

### 생성한 값으로 배열 생성

* `arange()`: 정수 범위로 배열 생성

In [14]:
import numpy as np
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

* `linspace()`: 범위 내에서 균등 간격의 배열 생성

In [15]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

* `logspace()`: 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [16]:
np.logspace(0.1,1,20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

### 랜덤값으로 배열 생성


* `random.random()`: 랜덤한 수의 배열 생성

In [17]:
np.random.random((3,3))

array([[0.59556177, 0.85826661, 0.85730218],
       [0.19000359, 0.18293077, 0.41529561],
       [0.80629763, 0.75380411, 0.95209515]])

* `random.randint()`: 일정 구간의 랜덤 정수의 배열 생성

In [18]:
np.random.randint(0,10,(3,3))

array([[0, 4, 4],
       [2, 2, 3],
       [4, 0, 9]])

* `random.normal()`: 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성
* 평균=0, 표준편차=1, 3 x 3 배열

In [19]:
np.random.normal(0,1,size =(3,3))

array([[-1.45681373, -1.37103948,  1.49537217],
       [ 0.84236663, -0.230669  ,  0.47447836],
       [-0.78978543,  0.81004549,  0.4036151 ]])

* `random.rand()`: 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성

In [20]:
np.random.rand(3,3)

array([[0.45147403, 0.05934855, 0.82169173],
       [0.96755364, 0.75170963, 0.68051779],
       [0.43900172, 0.45702637, 0.75475993]])

* `random.randn()`: 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성

In [21]:
np.random.randn(3,3)

array([[ 0.19731339,  0.83922351, -0.19639348],
       [-1.4839672 ,  1.02591419, -0.06004337],
       [-0.17598859, -0.58136327,  0.32558515]])

### 표준 데이터 타입

In [22]:
np.zeros(20,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [24]:
np.full((3,3), 1.0, dtype = float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 날짜/시간 배열 생성


In [25]:
date = np.array('2023-05-01', dtype=np.datetime64)
date

array('2023-05-01', dtype='datetime64[D]')

In [26]:
date + np.arange(12)

array(['2023-05-01', '2023-05-02', '2023-05-03', '2023-05-04',
       '2023-05-05', '2023-05-06', '2023-05-07', '2023-05-08',
       '2023-05-09', '2023-05-10', '2023-05-11', '2023-05-12'],
      dtype='datetime64[D]')

In [27]:
datetime = np.datetime64('2023-05-01 12:00')
datetime

numpy.datetime64('2023-05-01T12:00')

In [28]:
datetime= np.datetime64('2020-05-01 12:00:12.34', 'ns')
datetime

numpy.datetime64('2020-05-01T12:00:12.340000000')



---



## 배열 조회

### 배열 속성 정보

In [29]:
def array_info(array):
  print(array)
  print("ndim", array.ndim)
  print("shape", array.shape)
  print("dtype", array.dtype)
  print('size', array.size)
  print("itemsize", array.itemsize)
  print("nbytes", array.nbytes)
  print("strides", array.strides)

In [30]:
a1 = np.array([1, 2, 3, 4, 5])
array_info(a1)

[1 2 3 4 5]
ndim 1
shape (5,)
dtype int64
size 5
itemsize 8
nbytes 40
strides (8,)


In [31]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim 2
shape (3, 3)
dtype int64
size 9
itemsize 8
nbytes 72
strides (24, 8)


In [32]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim 3
shape (3, 3, 3)
dtype int64
size 27
itemsize 8
nbytes 216
strides (72, 24, 8)


### 인덱싱(Indexing)

In [33]:
print(a1)
print(a1[0])
print(a1[-1])

[1 2 3 4 5]
1
5


In [34]:
print(a2)
print(a2[0,0])
print(a2[0,1])
print(a2[0,-1])
print(a2[1,1])
print(a2[2,1])




[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
3
5
8


In [35]:
print(a3)
print(a3[0,0,0])
print(a3[1,1,1])
print(a3[2,2,2])



[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9


### 슬라이싱(Slicing)

* 슬라이싱 구문: `a[start:stop:step]`
* 기본값: start=0, stop=ndim, step=1

In [36]:
print(a1)
print(a1[0:2])
print(a1[0:1])
print(a1[::2])
print(a1[::-1])

[1 2 3 4 5]
[1 2]
[1]
[1 3 5]
[5 4 3 2 1]


In [37]:
print(a2)
print(a2[1])
print(a2[1,:1])
print(a2[:1,-1])
print(a2[1:,::-1])
print(a2[::1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[4]
[3]
[[6 5 4]
 [9 8 7]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


### 불리언 인덱싱(Boolean Indexing)

* 배열 각 요소의 선택 여부를 불리언(True or False)로 지정
* True 값인 인덱스의 값만 조회

In [38]:
print(a1)
bi = [False, True, True, False, True]
print(a1[bi])
bi = [False, False, False, False, True]
print(a1[bi])

[1 2 3 4 5]
[2 3 5]
[5]


In [39]:
print(a2)
bi = np.random.randint(0,2,(3,3), dtype = bool)
print(bi)
print(a2[bi])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ True  True False]
 [False False  True]
 [False  True  True]]
[1 2 6 8 9]


### 팬시 인덱싱(Fancy Indedxing)

In [40]:
print(a1)
print(a1[0], a1[2])
ind = [0,2]
print(a1[ind])
ind =np.array(
   [[0,1],
   [2,0]]
)
print(a1[ind])

[1 2 3 4 5]
1 3
[1 3]
[[1 2]
 [3 1]]


In [41]:
print(a2)
row = np.array([0,2])
col = np.array([1,2])
print(a2[row,col])
print(a2[row,:])
print(a2[:,col])
print(a2[row,1])
print(a2[1,col])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]
[[1 2 3]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[2 8]
[5 6]




---



## 배열 값 삽입/수정/삭제/복사

### 배열 값 삽입

* `insert()`: 배열의 특정 위치에 값 삽입
* axis를 지정하지 않으면 1차원 배열로 변환
* 추가할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [42]:
print(a1)
b1 = np.insert(a1,0,10)
print(b1)
print(a1)


[1 2 3 4 5]
[10  1  2  3  4  5]
[1 2 3 4 5]


In [43]:
print(a2)
b2 = np.insert(a2,1,10,axis = 0)
print(b2)
c2 = np.insert(a2,1,10,axis = 1)
print(c2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]


### 배열 값 수정

* 배열의 인덱싱으로 접근하여 값 수정

In [44]:
print(a1)
a1[0] = 1
a1[1] = 2
a1[2] = 3

print(a1)
a1[:1] = 9
print(a1)
i = np.array([1,3,4])
a1[i] = 0
print(a1)
a1[i] += 4
print(a1)

[1 2 3 4 5]
[1 2 3 4 5]
[9 2 3 4 5]
[9 0 3 0 0]
[9 4 3 4 4]


In [45]:
print(a2)
a2 [0,0] = 1
a2 [1,1] = 2
a2 [2,2] = 3
a2[0] =1
print(a2)

a2[1:,2] = 9
print(a2)
row = np.array([0,1])
col = np.array([1,2])
a2[row,col] = 0
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [4 2 6]
 [7 8 3]]
[[1 1 1]
 [4 2 9]
 [7 8 9]]
[[1 0 1]
 [4 2 0]
 [7 8 9]]


### 배열 값 삭제

* `delete()`: 배열의 특정 위치에 값 삭제
* axis를 지정하지 않으면 1차원 배열로 변환
* 삭제할 방향을 axis로 지정
* 원본 배열 변경없이 새로운 배열 반환

In [46]:
print(a1)
b1 = np.delete(a1,1)
print(b1)
print(a1)

[9 4 3 4 4]
[9 3 4 4]
[9 4 3 4 4]


In [47]:
print(a2)
b2 = np.delete(a2,1, axis=0)
print(b2)
c2 = np.delete(a2,1, axis=1)
print(c2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0 1]
 [7 8 9]]
[[1 1]
 [4 0]
 [7 9]]


### 배열 복사

* 리스트 자료형과 달리 배열의 슬라이스는 복사본이 아님

In [48]:
print(a2)
print(a2[:2,:2])
a2_sub = a2[:2,:2]
print(a2_sub)
a2_sub[:,1]=0
print(a2_sub)
print(a2)

[[1 0 1]
 [4 2 0]
 [7 8 9]]
[[1 0]
 [4 2]]
[[1 0]
 [4 2]]
[[1 0]
 [4 0]]
[[1 0 1]
 [4 0 0]
 [7 8 9]]



* `copy()`: 배열이나 하위 배열 내의 값을 명시적으로 복사

In [49]:
print(a2)
a2_sub_copy = a2[:2,:2].copy()
print(a2_sub_copy)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 0]
 [4 0]]




---



## 배열 변환

### 배열 전치 및 축 변경

In [50]:
print(a2)
print(a2.T)

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [51]:
print(a3)
print(a3.T)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 1 1]
  [4 4 4]
  [7 7 7]]

 [[2 2 2]
  [5 5 5]
  [8 8 8]]

 [[3 3 3]
  [6 6 6]
  [9 9 9]]]


In [52]:
print(a2)
print(a2.swapaxes(1,0))

[[1 0 1]
 [4 0 0]
 [7 8 9]]
[[1 4 7]
 [0 0 8]
 [1 0 9]]


In [53]:
print(a3)
print(a3.swapaxes(0,1))
print(a3.swapaxes(1,2))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]
  [4 5 6]]

 [[7 8 9]
  [7 8 9]
  [7 8 9]]]
[[[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]

 [[1 4 7]
  [2 5 8]
  [3 6 9]]]


### 배열 재구조화


* `reshape()`: 배열의 형상을 변경

In [54]:
n1 = np.arange(1,10)
print(n1)
print(n1.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


* `newaxis()`: 새로운 축 추가

In [55]:
print(n1)
print(n1[np.newaxis, :5])
print(n1[ :5, np.newaxis])

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


### 배열 크기 변경

* 배열 모양만 변경

In [56]:
n2 = np.random.randint(0,10,(2,5))
print(n2)
n2.resize((5,2))
print(n2)


[[2 2 3 6 4]
 [2 4 1 2 2]]
[[2 2]
 [3 6]
 [4 2]
 [4 1]
 [2 2]]


* 배열 크기 증가
* 남은 공간은 0으로 채워짐

In [57]:
n2.resize((5, 5),refcheck=False)
print(n2)

[[2 2 3 6 4]
 [2 4 1 2 2]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


* 배열 크기 감소
* 포함되지 않은 값은 삭제됨

In [58]:
n2.resize((3,3),refcheck=False)
print(n2)

[[2 2 3]
 [6 4 2]
 [4 1 2]]


### 배열 추가

* `append()`: 배열의 끝에 값 추가

In [59]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.arange(10,19).reshape(3,3)
print(b2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


* axis 지정이 없으면 1차원 배열 형태로 변형되어 결합

In [60]:
c2 = np.append(a2,b2)
print(c2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


* axis를 0으로 지정
* shape[0]을 제외한 나머지 shape은 같아야 함

In [61]:
c2 = np.append(a2,b2,axis=0)
print(c2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


* axis를 1로 지정
* shape[1]을 제외한 나머지 shape은 같아야 함

In [62]:
c2 = np.append(a2,b2,axis=1)
print(c2)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


### 배열 연결

* `concatenate()`: 튜플이나 배열의 리스트를 인수로 사용해 배열 연결

In [63]:
a1 = np.array([1,3,5])
b1 = np.array([2,4,6])
np.concatenate([a1,b1])


array([1, 3, 5, 2, 4, 6])

In [64]:
c1 = np.array([7,8,9])
np.concatenate([a1,b1,c1])

array([1, 3, 5, 2, 4, 6, 7, 8, 9])

In [65]:
a2 = np.array([
    [1,2,3],
    [4,5,6]
])
np.concatenate([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
a2 = np.array([
    [1,2,3],
    [4,5,6]
])
np.concatenate([a2,a2],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `vstack()`: 수직 스택(vertical stack), 1차원으로 연결

In [67]:
np.vstack([a2,a2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* `hstack()`: 수평 스택(horizontal stack), 2차원으로 연결

In [68]:
np.hstack([a2,a2])

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* `dstack()`: 깊이 스택(depth stack), 3차원으로 연결

In [69]:
np.dstack([a2,a2])


array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

* `stack()`: 새로운 차원으로 연결

In [70]:
np.stack([a2,a2])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

### 배열 분할

* `split()`: 배열 분할

In [71]:
a1 = np.arange(0,10)
print(a1)
b1,c1 = np.split(a1,[5])
print(b1, c1)
b1,c1,d1,e1,f1 = np.split(a1,[2,4,6,8])
print(b1,c1,d1,e1,f1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4] [5 6 7 8 9]
[0 1] [2 3] [4 5] [6 7] [8 9]


* `vsplit()`: 수직 분할, 1차원으로 분할

In [72]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.vsplit(a2,[2])
print(b2)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[7 8 9]]


* `hsplit()`: 수평 분할, 2차원으로 분할

In [73]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2,c2 = np.hsplit(a2,[2])
print(b2)
print(c2) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]


* `dsplit()`: 깊이 분할, 3차원으로 분할

In [74]:
a2 = np.arange(1,28).reshape(3,3,3)
print(a3)
b3,c3 = np.dsplit(a3,[2])
print(b3)
print(c3) 

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[[[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]

 [[1 2]
  [4 5]
  [7 8]]]
[[[3]
  [6]
  [9]]

 [[3]
  [6]
  [9]]

 [[3]
  [6]
  [9]]]




---



## 배열 연산

* NumPy의 배열 연산은 벡터화(vectorized) 연산을 사용
* 일반적으로 NumPy의 범용 함수(universal functions)를 통해 구현
* 배열 요소에 대한 반복적인 계산을 효율적으로 수행

### 브로드캐스팅(Broadcasting)

In [75]:
a1 = np.array([1,2,3])
print(a1)
print(a1+5)

[1 2 3]
[6 7 8]


In [76]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
print(a1+a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [77]:
b2 = np.array([1,2,3]).reshape(3,1)
print(b2)
print(a1+b2)

[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


### 산술 연산(Arithmetic Operators)

In [78]:
a1 = np.arange(1,10)
print(a1)
print(a1+1)
print(np.add(a1,10))
print(a1 - 2)
print(np.subtract(a1,10))
print(-a1)
print(np.negative(a1))
print(np.multiply(a1,2))
print(a1/2)
print(np.divide(a1,2))
print(a1//2)
print(np.floor_divide(a1,2))
print(a1 **2)
print(np.power(a1,2))
print(a1 % 2)
print(np.mod(a1,2))

[1 2 3 4 5 6 7 8 9]
[ 2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19]
[-1  0  1  2  3  4  5  6  7]
[-9 -8 -7 -6 -5 -4 -3 -2 -1]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[-1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 2  4  6  8 10 12 14 16 18]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 1 2 2 3 3 4 4]
[0 1 1 2 2 3 3 4 4]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1 0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0 1]


In [79]:
a1 = np.arange(1,10)
print(a1)
b1 = np.random.randint(1,10,size = 9)
print(b1)
print(a1 + b1)
print(a1 - b1)
print(a1 * b1)
print(a1 / b1)
print(a1// b1)
print(a1**b1)

[1 2 3 4 5 6 7 8 9]
[2 5 2 1 9 3 5 2 1]
[ 3  7  5  5 14  9 12 10 10]
[-1 -3  1  3 -4  3  2  6  8]
[ 2 10  6  4 45 18 35 16  9]
[0.5        0.4        1.5        4.         0.55555556 2.
 1.4        4.         9.        ]
[0 0 1 4 0 2 1 4 9]
[      1      32       9       4 1953125     216   16807      64       9]


In [80]:
a2 = np.arange(1,10).reshape(3,3)
print(a2)
b2 = np.random.randint(1,10,size = (3,3))
print(b2)
print(a2 + b2)
print(a2 - b2)
print(a2 * b2)
print(a2 / b2)
print(a2 // b2)
print(a2 ** b2)
print(a2 % b2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 1 6]
 [6 2 9]
 [6 6 6]]
[[ 3  3  9]
 [10  7 15]
 [13 14 15]]
[[-1  1 -3]
 [-2  3 -3]
 [ 1  2  3]]
[[ 2  2 18]
 [24 10 54]
 [42 48 54]]
[[0.5        2.         0.5       ]
 [0.66666667 2.5        0.66666667]
 [1.16666667 1.33333333 1.5       ]]
[[0 2 0]
 [0 2 0]
 [1 1 1]]
[[       1        2      729]
 [    4096       25 10077696]
 [  117649   262144   531441]]
[[1 0 3]
 [4 1 6]
 [1 2 3]]


#### 절대값 함수(Absolute Function)

* `absolute()`, `abs()`: 내장된 절대값 함수

In [82]:
a1 = np.random.randint(-10,10, size =5)
print(a1)
print(np.abs(a1))

[-3  0  0  6  5]
[3 0 0 6 5]


#### 제곱/제곱근 함수

* `square`, `sqrt`: 제곱, 제곱근 함수

In [84]:
print(a1)
print(np.square(a1))
print(np.sqrt(a1))

[-3  0  0  6  5]
[ 9  0  0 36 25]
[       nan 0.         0.         2.44948974 2.23606798]


<ipython-input-84-4e034cb7ea92>:3: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(a1))


#### 지수와 로그 함수 (Exponential and Log Function)

In [85]:
a1 = np.random.randint(1,10,size = 5)
print(a1)
print(np.exp(a1))
print(np.exp2(a1))
print(np.power(a1,2))

[7 8 7 5 5]
[1096.63315843 2980.95798704 1096.63315843  148.4131591   148.4131591 ]
[128. 256. 128.  32.  32.]
[49 64 49 25 25]


In [86]:
print(a1)
print(np.log(a1))
print(np.log2(a1))
print(np.log10(a1))

[7 8 7 5 5]
[1.94591015 2.07944154 1.94591015 1.60943791 1.60943791]
[2.80735492 3.         2.80735492 2.32192809 2.32192809]
[0.84509804 0.90308999 0.84509804 0.69897    0.69897   ]


#### 삼각 함수(Trigonometrical Function)


In [87]:
t = np.linspace(0,np.pi,3)
print(t)
print(np.sin(t))
print(np.cos(t))
print(np.tan(t))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [88]:
x = [-1,0,1]
print(x)
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))

[-1, 0, 1]
[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]
[-0.78539816  0.          0.78539816]


### 집계 함수(Aggregate Functions)

#### sum(): 합 계산

In [90]:
a2 = np.random.randint(1,10, size=(3,3))
print(a2)
print(a2.sum(),np.sum(a2))
print(a2.sum(axis = 0),np.sum(a2,axis = 0))
print(a2.sum(axis = 1),np.sum(a2,axis = 1))



[[9 3 1]
 [4 9 8]
 [7 7 7]]
55 55
[20 19 16] [20 19 16]
[13 21 21] [13 21 21]


#### cumsum(): 누적합 계산

In [91]:
print(a2)
print(np.cumsum(a2))
print(np.cumsum(a2,axis = 0))
print(np.cumsum(a2,axis = 1))

[[9 3 1]
 [4 9 8]
 [7 7 7]]
[ 9 12 13 17 26 34 41 48 55]
[[ 9  3  1]
 [13 12  9]
 [20 19 16]]
[[ 9 12 13]
 [ 4 13 21]
 [ 7 14 21]]


#### diff(): 차분 계산

In [92]:
print(a2)
print(np.diff(a2))
print(np.diff(a2,axis = 0))
print(np.diff(a2,axis = 1))

[[9 3 1]
 [4 9 8]
 [7 7 7]]
[[-6 -2]
 [ 5 -1]
 [ 0  0]]
[[-5  6  7]
 [ 3 -2 -1]]
[[-6 -2]
 [ 5 -1]
 [ 0  0]]


[[9 3 1]
  
  -6 -2
 
 [4 9 8]
  
   5 -1
   
[7 7 7]]



#### prod(): 곱 계산

In [93]:
print(a2)
print(np.prod(a2))
print(np.prod(a2,axis = 0))
print(np.prod(a2,axis = 1))

[[9 3 1]
 [4 9 8]
 [7 7 7]]
2667168
[252 189  56]
[ 27 288 343]


#### cumprod(): 누적곱 계산

In [95]:
print(a2)
print(np.cumprod(a2))
print(np.cumprod(a2,axis = 0))
print(np.cumprod(a2,axis = 1))

[[9 3 1]
 [4 9 8]
 [7 7 7]]
[      9      27      27     108     972    7776   54432  381024 2667168]
[[  9   3   1]
 [ 36  27   8]
 [252 189  56]]
[[  9  27  27]
 [  4  36 288]
 [  7  49 343]]


#### dot()/matmul(): 점곱/행렬곱 계산

In [96]:
print(a2) 
b2 = np.ones_like(a2)
print(b2)
print(np.dot(a2,b2))
print(np.matmul(a2,b2))

[[9 3 1]
 [4 9 8]
 [7 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[13 13 13]
 [21 21 21]
 [21 21 21]]
[[13 13 13]
 [21 21 21]
 [21 21 21]]


a2 
[
  [9 3 1]
 
 [4 9 8]
 
 [7 7 7]]

b2
[
  [1 1 1]
 
 [1 1 1]
 
 [1 1 1]]


 9*1 + 3*1 + 1*1 = 13
 
 7*1 + 7*1 + 7*1 = 21

#### tensordot(): 텐서곱 계산

In [98]:
print(a2)
print(b2)
print(np.tensordot(a2,b2))
print(np.tensordot(a2,b2,axes=0))
print(np.tensordot(a2,b2,axes=1))

[[9 3 1]
 [4 9 8]
 [7 7 7]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
55
[[[[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[3 3 3]
   [3 3 3]
   [3 3 3]]

  [[1 1 1]
   [1 1 1]
   [1 1 1]]]


 [[[4 4 4]
   [4 4 4]
   [4 4 4]]

  [[9 9 9]
   [9 9 9]
   [9 9 9]]

  [[8 8 8]
   [8 8 8]
   [8 8 8]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]]
[[13 13 13]
 [21 21 21]
 [21 21 21]]


#### cross(): 벡터곱

#### inner()/outer(): 내적/외적

#### mean(): 평균 계산

#### std(): 표준 편차 계산

#### var(): 분산 계산

#### min(): 최소값

#### max(): 최대값

#### argmin(): 최소값 인덱스

#### argmax(): 최대값 인덱스

#### median(): 중앙값

#### percentile(): 백분위 수



#### any()

#### all()

### 비교 연산(Comparison Operators)


#### 불리언 연산자(Boolean Operators)


### 배열 정렬

#### 부분 정렬

* `partition()`: 배열에서 k개의 작은 값을 반환

## 배열 입출력




---

